version: "3.9"

volumes:
  astramongodb:

services:
    zip-rp:
        build: .
        environment:
          WORK_DIR: "/workspace"
          OUT_DIR: "/build"
          NAME: "${NAME}"
        volumes:
          - "${WORKSPACE}:/workspace"
          - "${OUT_DIR}:/build"
        command: bash /workspace/create_zip.sh --force-rebuild-dir --zip